Feature/icon-0.1.0
prgrms-fe-devcourse/FEDC5_looky_heejin pull request #14
Opened 2023-12-27 11:11 UTC by hellosonic-r

## 📌 기능 설명 
- 아이콘 컴포넌트를 구현했습니다.
- looky에 쓰이는 아이콘 이름을 constants/index.ts에서 별도로 관리하고 있습니다. Import 해서 사용 가능합니다.
- 

## 👩‍💻 요구 사항과 구현 내용 

## ✅ 피드백 반영사항  

## ✅ PR 포인트 & 궁금한 점

2023-12-27 12:55 UTC, OhWonJu requested changes
고생하셨습니다.
첫 브랜치 PR 축하드립니당!

2023-12-27 14:08 UTC, joyswim commented on src/components/common/Icon/Icon.tsx
> +    },'wght' ${processedWeight}`,
p5: 구글 폰트 link 태그를 뜯어보진 않았는데 이런 옵션도 바꿀 수 있군요!

2023-12-27 14:08 UTC, joyswim approved these changes

2023-12-27 14:26 UTC, OhWonJu commented on src/components/common/Icon/Icon.tsx
> +    },'wght' ${processedWeight}`,
오 신기하네요..!

2023-12-28 01:47 UTC, hellosonic-r commented on src/constants/index.ts
> +export const SEND_ICON: string = "send";
네네!! 수정하드록 할게요~!!

2023-12-28 01:48 UTC, hellosonic-r commented on src/components/common/Icon/Icon.tsx
> +    },'wght' ${processedWeight}`,
저두 이번에 덕분에 처음 알게되었네요 ㅋㅋㅋ

2023-12-28 01:53 UTC, SoJuSo reviewed
고생하셨습니다 민호님!
원주님이 언급하신 해결사항만 수정되면 merge해도 될 것 같습니다!

2023-12-28 01:55 UTC, OhWonJu approved these changes

2023-12-28 01:56 UTC, merged