[♻️refactor]: 홈페이지 성능 최적화 및 이미지 스프라이트 적용
prgrms-fe-devcourse/FEDC5_looky_heejin pull request #161
Opened 2024-08-27 16:42 UTC by joyswim

## 📝작업 내용
홈페이지 성능 최적화를 진행하고 이미지 스프라이트 적용했습니다.

### ⚠️ 공지사항
- package.json이 변경되었습니다.
리소스 압축 vite-plugin-compression이 설치되었습니다. 머지 후 `npm i`를 실행해주세요.
- 기존 icons 상수를 객체로 변경했습니다. ([/contants/icons.ts](https://github.com/prgrms-fe-devcourse/FEDC5_looky_heejin/compare/refactor/125-ImageOptimization?expand=1#diff-df0509a73ffe656fcbcf496832f367035053265c916df2cb8f66febe11042181))

### 🔍 세부내용
- Image 컴포넌트 교체
- 지연 로드와 코드 스플리팅 lazy, Suspense 적용
- 라우팅 페이지, 모달 뷰 컴포넌트에 적용
- 리소스 압축 vite-plugin-compression 라이브러리 사용
- Icon 이미지 스프라이트

## 💬리뷰 요구사항
- 아이콘을 이미지 스프라이트로 변경하면서 link 태그를 삭제했는데 유지하는 게 좋을지 의견이 궁금합니다.([index.html](https://github.com/prgrms-fe-devcourse/FEDC5_looky_heejin/compare/refactor/125-ImageOptimization?expand=1#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051))

2024-09-02 05:04 UTC, SoJuSo requested changes
반복 작업이 꽤 많았네요ㅠㅠ 고생하셨어요 누나! 라이브러리 관련된 리뷰 한번만 봐주세요!

2024-09-02 05:04 UTC, SoJuSo commented on package.json
> +    "vite-plugin-compression": "^0.5.1"
P2; 라이브러리 보완이 필요할 것 같습니다!
기존에 gzip 압축에 사용되던, 그리고 현재 프로젝트에 적용된 `vite-plugin-compression`의 경우 유지보수가 상당히 오랜기간 진행되지 않고 있는 문제점이 있습니다! 따라서 `vite-plugin-compression2`라는 새로운 라이브러리를 적용하는게 더 괜찮지 않을까 제안드립니다!

`vite-plugin-compression2` 라이브러리 제작자가 실제로 2버전을 만든 이유를 유지보수의 문제라고 서술하더라구요! 아래 해당 Q&A 문서 링크 드립니당!
https://github.com/nonzzz/vite-plugin-compression/blob/master/Q&A.md

2024-09-04 12:51 UTC, SoJuSo approved these changes

2024-09-04 12:53 UTC, joyvy commented on package.json
> +    "vite-plugin-compression": "^0.5.1"
의견 반영하여 vite-plugin-compression2로 적용했습니다. 정보 공유 감사해요! 👍

2024-09-04 12:53 UTC, merged