Feature/bottom nav bar 0.1.0
prgrms-fe-devcourse/FEDC5_looky_heejin pull request #24
Opened 2023-12-30 15:25 UTC by hellosonic-r

## 📌 기능 설명 

https://github.com/prgrms-fe-devcourse/FEDC5_looky_heejin/assets/124658938/99fecc3f-e5fc-461d-9500-8a8b6a8efdb0

- react-router-dom의 useLocation 훅을 사용하여 pathname을 가져오고, pathname에 따라 navBar를 렌더링할지 여부를 판단하고 아이콘의 색상을 다르게 렌더링 합니다.

## 👩‍💻 요구 사항과 구현 내용 

## ✅ 피드백 반영사항  

## ✅ PR 포인트 & 궁금한 점

2023-12-31 03:35 UTC, OhWonJu requested changes
구현하시느라 고생 많으셨습니다.
전체적인 기능상 문제는 없는것으로 보이나,
추후에 있을 작업들과의 연계를 수월하게 할 수 있는 부분이 보여서 이 부분 참고해주시면 감사할 것 같습니다.

2023-12-31 03:35 UTC, OhWonJu commented on src/components/common/Navigator/BottomNavBar.tsx
> +  ];
p5; 요 상수는 컴포넌트 외부로 빼도 정상 동작할 것 같습니다.
globalSingletone 느낌으로 말이죠!

2023-12-31 03:35 UTC, OhWonJu commented on src/components/common/Navigator/BottomNavBar.tsx
> +  );
p4; 좀 더 구체적인 함수명을 사용하면 어떨까 싶습니다.
handleIconClick 이나 handleNavButtonClick 같은거요!

2023-12-31 03:35 UTC, OhWonJu commented on src/components/common/Navigator/BottomNavBar.tsx
> +    showNavBar && (
p5; 이전 맨토셨던 노아님께서는
이러한 경우 별도 if 문으로 렌더링을 분리하시는 것을 선호하신다고 하셨습니다. 저도 그분의 이야기를 듣고 나서 
if 문으로 분리할 수 있는 경우 분리하는게 좀 더 가독성에 좋다고 생각하는 편입니다. 

예를 들어

```
if(!showNavBar) {
 return null
} 

return (< ... ///    .... />)
```

이런식으로요!

기능상으로는 문제가 없을 것 같으므로 참고 정도만 해주셔도 됩니다!

2023-12-31 03:35 UTC, OhWonJu commented on src/routes/index.tsx
> +        <BottomNavBar />
p3; 추후에 레이아웃에 패딩이나, 마진값이 생기면 바텀내비게이터도 그 패딩에 맞게 줄어들게 되겠죠?
레이아웃 외부로 빼내도 문제가 없다면 빼내는게 추후에 레이아웃 작업에 있어서 수월할 것 같습니다.

2023-12-31 03:37 UTC, OhWonJu commented on src/components/common/Navigator/BottomNavBar.tsx
> +        <IconWrapper onClick={() => handleClick("/search")}>
p5; 기존에 구현된 Button 컴포넌트를 사용해보는 것은 어떤가요?
Ripple 이팩트는 사실 일반적인 버튼보다는 Icon 이 들어있는 작은 버튼에 잘 어울리는 것 같거든요!

2023-12-31 04:11 UTC, joyswim commented on src/components/common/Navigator/BottomNavBar.tsx
> +  );
p5 : useMemo로 연산 최적화하신 점 좋습니다!

2023-12-31 04:14 UTC, joyswim approved these changes

2023-12-31 09:54 UTC, hellosonic-r commented on src/components/common/Navigator/BottomNavBar.tsx
> +  ];
네네! 반영했습니다.
기존처럼 모든 상수를 export하지 않고 하나의 객체에 각각의 key에 해당하는 pathname을 사용할 수 있도록 상수 객체를 생성하는 식으로 분리했는데 요것두 괜찮을까요?

2023-12-31 09:54 UTC, hellosonic-r commented on src/components/common/Navigator/BottomNavBar.tsx
> +  );
그렇네요 ㅎㅎ 반영했습니다~!!👍

2023-12-31 09:54 UTC, hellosonic-r commented on src/components/common/Navigator/BottomNavBar.tsx
> +    showNavBar && (
오호! 반영했습니다 요렇게하니까 확실히 가독성이 훨씬 좋아보이네요!

2023-12-31 09:55 UTC, hellosonic-r commented on src/routes/index.tsx
> +        <BottomNavBar />
반영 했습니다!!

2023-12-31 09:56 UTC, hellosonic-r commented on src/components/common/Navigator/BottomNavBar.tsx
> +        <IconWrapper onClick={() => handleClick("/search")}>
엇 말씀 듣고보니 그럴 것 같네요
저두 바꿔보고싶은 욕심이 있어서 시도중인데 왠지 잘 되질 않네요 ㅠ 
시도해보다가 막히면 내일 물어보겠슴다 ㅎㅎ

2024-01-01 02:00 UTC, OhWonJu approved these changes
고생하셨습니다!
상수로 분리한 것 좋습니다! 다만 제가 말씀드린 의도랑 약간 다른 방향이였네요!
참고정도만 해주시면 될 것 같습니다.

2024-01-01 02:00 UTC, OhWonJu commented on src/components/common/Navigator/BottomNavBar.tsx
> +  ];
아하 제 의도가 약간 잘 못 전달된것 같네여!
```
const NAV_INABLE_PATH = [ .... ] 

const BottomNavBar = () => {

...}
```

요런식을 말씀드린거였어요!

2024-01-01 02:00 UTC, SoJuSo approved these changes

2024-01-01 02:01 UTC, merged