Feature/TopNavBar-0.1.0
prgrms-fe-devcourse/FEDC5_looky_heejin pull request #34
Opened 2024-01-02 14:38 UTC by hellosonic-r

## 📝작업 내용

- TopNavBar 기본 기능 구현 및 기본 깡통 레이아웃 
- pathname에 따라 TopNavBar에 렌더링될 element가 각각 다르고, element들은 elements 디렉토리에 분리했습니다.
- Navbar의 검색창에서 입력한 값이 리덕스 스토어에 저장됩니다.

### ✨스크린샷 (선택)

https://github.com/prgrms-fe-devcourse/FEDC5_looky_heejin/assets/124658938/66ff3e94-d90d-4f27-a722-2296d95c83ac
## 💬리뷰 요구사항(선택)

- 걱정되는 부분이 구현에 우선순위가 있다보니 스타일 속성 사용법이 너무 엉망입니다. 모바일에서도 무너지지 않고 잘 보여지긴 하는데 맞는지 모르겠네요,, 고쳐야할 부분 있다면 청학동 매운맛 스타일로 가르침 부탁드립니다. 추후 공부하고 리팩토링 해보도록 하겠습니다.
- react-hook-form 과 redux 사용법이 올바른지 궁금합니다.

2024-01-03 12:02 UTC, SoJuSo commented on src/pages/NotificationsPage/index.tsx
알림페이지를 까먹었었군요ㅠㅠ

2024-01-03 12:05 UTC, SoJuSo commented on src/components/common/Navigator/TopNavBar/Elements/SearchBar.tsx
> +              message: "2자 이상 입력해주세요",
P5; 에러 메세지는 있는데 따로 출력해주는 기능이 없네요! 추후 tooltip 같은 걸로 띄워줘도 좋을 것 같아요

2024-01-03 12:08 UTC, SoJuSo commented on src/components/common/Navigator/TopNavBar/TopNavBar.tsx
> +            <PageTitle title="빈티지"></PageTitle> // 데이터 붙여야함
확실히 타이틀에는 뭔가 멋진 글꼴을 적용해야겠네욥.. 윈도우 기본 글꼴에서는....

2024-01-03 12:13 UTC, SoJuSo commented on src/components/common/Navigator/TopNavBar/Elements/SearchBar.tsx
> +  width: 146%;
P4; 이 부분에서 width가 왜 146%인지 화면이랑 같이 봤는데 음... 서치페이지에 경우 스타일링 코드를 다르게 주는 방향으로 진행해보면 어떨까요? 또한 각각의 파트를 감싸는 div의 위치, 역할들에 약간 조율이 필요할 것 같습니다..! 요거는 추후에 리팩토링하면서 고민하시면 좋을 것 같아요!

2024-01-03 12:16 UTC, SoJuSo commented on src/components/common/Navigator/TopNavBar/TopNavBar.tsx
> +            <LogoImage onClick={() => handleIconClick(PathName.HOME)} />
P5; 홈으로 돌아가게 해주는 로직이 있었군요! 개인적으로 좋다고 생각은 합니다! 다만 다른 페이지로 갔을 때 로고가 전부 뒤로가기 버튼이 되어버리는데 이 부분을 잘 활용할 방법이 어떤게 있을까요.. 같이 고민해봐요!

2024-01-03 12:17 UTC, SoJuSo commented on src/components/common/Navigator/TopNavBar/Elements/SearchBar.tsx
> +    console.log(keyword);
이전에 검색했던 값이 리덕스 스토어에 잘 저장되어있더라고요 bb

2024-01-03 12:18 UTC, SoJuSo commented on src/components/common/Navigator/TopNavBar/Elements/ChatNotificationIconsBox.tsx
P5; 아이콘 위치 리팩토링 하신건가요! 지금은 위치 안 어긋나보이네요!

2024-01-03 15:24 UTC, joyswim commented on src/store/reducers/searchReducer.ts
SearchPage 만들면서 고민한 부분인데 잘 구현해주셨네요!

2024-01-03 15:32 UTC, joyswim commented on src/components/common/Navigator/TopNavBar/TopNavBar.tsx
> +  width: ${({ $width }) => $width && $width};
만약 1:3:1 비율을 유지하고 싶으셨다면 width 대신 flex-grow 속성을 사용해보시면 좋을 것 같아요!
`flex-grow: 1`
`flex-grow: 3`

2024-01-03 15:39 UTC, joyswim commented on src/components/common/Navigator/TopNavBar/Elements/SearchBar.tsx
> +  width: 146%;
wrapper 속성이 %이면 상위 컴포넌트에서 또 wrapper가 필요하지 않을까 생각됩니다. 현재는 SearchBarWrapper의 상위 컴포넌트가 안 보여서 판단이 불가능하지만 레이아웃 잡으실 때 어려울 수도 있겠다고 생각했어요!

2024-01-03 15:41 UTC, joyswim commented on src/components/common/Navigator/TopNavBar/Elements/SearchBar.tsx
> +  }
:placeholder 가상선택자가 있었네요. 생각못했습니다

2024-01-03 15:48 UTC, joyswim commented on src/components/common/Navigator/TopNavBar/Elements/SearchBar.tsx
> +  & {
& 단독으로 쓰인 것은 부모 선택자로 쓰인 걸까요?

2024-01-03 15:51 UTC, joyswim approved these changes
민호님 고생하셨습니다! reducer로 상태 관리하신 점이 좋았습니다. 저도 reducer를 직접 구현해 보고 싶네요!

2024-01-04 01:14 UTC, OhWonJu requested changes
고생하셨습니다.
전체적인 로직은 괜찮은것 같아요!

2024-01-04 01:14 UTC, OhWonJu commented on src/components/common/Navigator/TopNavBar/Elements/SearchBar.tsx
> +              message: "2자 이상 입력해주세요",
p5; 기존 Input 공용 컴포넌트를 사용하는데 어려움이 있는 케이스일까요?
그게 아니라면 공용 컴포넌트를 사용해보는게 좋지 않을까 싶습니다.
form 내부를 Input 컴포넌트가 100% 차지하게 한뒤
Input 컴포넌트에 좌우 padding 을 주고 그 공간에 Icon 들을 absolute 로 위치시키면 의도하신 구현을 똑같이 하실 수 있을 것  같습니다.

2024-01-04 02:47 UTC, hellosonic-r commented on src/components/common/Navigator/TopNavBar/Elements/ChatAvatars.tsx
> +            style={{ width: "32px" }} // 임시값 리팩토링 필요
아 요부분은 XS로 설정한 사이즈가 navbar에 적용시키기엔 좀 커서 강제로 사이즈를 설정해두었습니다 수영님이 아바타 컴포넌트 리팩토링해주셔서 반영 예정입니다!

2024-01-04 02:48 UTC, hellosonic-r commented on src/components/common/Navigator/BottomNavBar/BottomNavBar.tsx
> +          rippleColor={theme.symbol_color}
아 네네! 저두 같은 의견인데, 컬러 고르기가 만만치 않더라구요,, 나중에 스크럼때 다같이 고민해보고 색상 정해보면 좋을 것 같아요, 그때 반영하도록 하겠습니다!

2024-01-04 02:51 UTC, joyswim commented on src/components/common/Navigator/TopNavBar/TopNavBar.tsx
> +  height: 3rem;
p4: NAV의 height 값은 원주님이 만들어 놓으신 NAV_HEIGHT 상수를 사용해주시면 좋을 것 같습니다~ 현재는 3.75rem으로 설정되어 있습니다.  BottomNavBar도 동일합니다!
```
import { NAV_HEIGHT } from "@/constants/uiConstants";

const TopNavBarWrapper = styled.nav`
  height: ${NAV_HEIGHT}rem
`
```

2024-01-04 02:56 UTC, hellosonic-r commented on src/components/common/Navigator/BottomNavBar/BottomNavBar.tsx
> +  const NAV_INABLE_PATH = [
요부분 리팩토링이 꼭 필요할 것 같긴 합니다.
지금 원주님 말씀대로 nav가 보여져야 할 페이지가 많아서 보여지지 않을 페이지들을 나열하고 처리하면 코드도 간략해지고 깔끔할 것 같은데 문제는 Notfound 페이지 경로가 들어올 때입니다 ㅠ 예를들어 "dfasfasfasfsdafasdfsadgsdfavz" 이런 pathname이 들어왔을 때 현재로써는 그게 notfound 경로라고 알 수가 없는 상황입니다.
여러가지 고민들을 해봤는데, notfound페이지가 렌더될 때 리덕스 스토어에 isNavShow 와같은 상태를 false로 변경시키고 navbar를 렌더하지 않는 방법이 있을 것 같습니다.

제가 시도해본 방법이나, 추후 리팩토링 방향성 관련해서 이슈 탭에 정리해 놓겠습니다. 우선 의미에 부합하는 변수명으로 수정만 해둘게요 😭

2024-01-04 03:20 UTC, OhWonJu commented on src/components/common/Navigator/TopNavBar/TopNavBar.tsx
> +  height: 3rem;
임의로 3.75rem 으로 해놓은거라 맞춰서 수정하심 될것가탕요

2024-01-04 03:29 UTC, hellosonic-r commented on src/components/common/Navigator/TopNavBar/Elements/SearchBar.tsx
> +              message: "2자 이상 입력해주세요",
@SoJuSo 오 그러네요 챌린지로 나중에 해봐야겠네요 ㅋㅋㅋ
@OhWonJu 반영했습니다~~ 감사합니다!

2024-01-04 03:32 UTC, hellosonic-r commented on src/components/common/Navigator/TopNavBar/Elements/SearchBar.tsx
> +  width: 146%;
@SoJuSo @joyswim 스타일 적용하는데에 좀 의문이 많이들었네요.. ㅋㅋㅋ 진짜 구현에 급급했던 중구난방한 속성들.. 이따가 시간 되실때 코드 같이 보면서 스타일 같이 적용해보면 좋을 것 같아요!

2024-01-04 03:34 UTC, hellosonic-r commented on src/components/common/Navigator/TopNavBar/TopNavBar.tsx
> +            <LogoImage onClick={() => handleIconClick(PathName.HOME)} />
아 네네 ! 사실 일반적인 웹사이트의 경우 Navbar에 로고 이미지가 박혀있고, 그 로고 이미지를 클릭하면 홈으로 돌려보내잖아요 
근데 저희는 모바일 레이아웃의 웹서비스이기도하고,, 또 bottom nav에 홈 버튼이 있어서 로고이미지 클릭시 굳이 홈으로 안돌려보내도되지ㅣ만 뭔가 사용자 경험에서 봤을때 '이부분은 클릭할 수 있을거야' 라는 생각을 사용자들이 하지 않을까 싶어서 넣어봤습니다..! 같이 고민해봐요

2024-01-04 03:35 UTC, hellosonic-r commented on src/components/common/Navigator/TopNavBar/Elements/ChatNotificationIconsBox.tsx
네네! 조금 수정했어요 ㅎㅎ

2024-01-04 03:41 UTC, hellosonic-r commented on src/components/common/Navigator/TopNavBar/TopNavBar.tsx
> +  width: ${({ $width }) => $width && $width};
오오 그렇네요 ㅎㅎ 감사합니다!!

2024-01-04 03:43 UTC, hellosonic-r commented on src/components/common/Navigator/TopNavBar/Elements/SearchBar.tsx
> +  & {
오잉?? 그러게요? 왜 저렇게 해놨지.. 수정했습니다~!!

2024-01-04 03:56 UTC, OhWonJu approved these changes
고생하셨습니다!!!

2024-01-04 03:59 UTC, merged