Feature/route 2.1.0
prgrms-fe-devcourse/FEDC5_looky_heejin pull request #35
Opened 2024-01-03 02:27 UTC by OhWonJu

## 📝작업 내용

라우터상에서 인증이 필요한 접근에 대해 가지고 있는 토큰 값을 통해 auth-user 를 서버로 요청하고
사용자 정보를 확인 후 접근을 허용하도록 합니다.

- 라우터 경로를 일부 수정했습니다.
- 수정에 따라 bottomNav 에 profile 을 profile/id 에 맞게 변경했습니다.
  - 민호님 이부분 참고해서 변경해주시면 좋을 것 같습니다.

2024-01-03 02:30 UTC, SoJuSo commented
FileChange 탭에 들어갔는데...이미 dev에 있는 요소들이 추적이 안되고 있는 것 같습니다.
그리고 또 merge Conflict가 나네욥...

2024-01-03 05:25 UTC, joyswim commented on src/routes/index.tsx
> +              <AuthRoute path="/profile/:id" element={<ProfilePage />} />
p4: "/profile"과 "/profile/:id"의 element가 동일합니다. id로 접근하는 페이지를 따로 만들지 않고 ProfilePage 컴포넌트에서 해결하면 되나요?

2024-01-03 10:41 UTC, OhWonJu commented on src/routes/index.tsx
> +              <AuthRoute path="/profile/:id" element={<ProfilePage />} />
저는 그게 맞는 방법이 아닐까 싶네요.
profile / profile/:id  별도의 페이지가 필요한 경우가 있을까요?

2024-01-03 12:27 UTC, SoJuSo approved these changes
여러 가지 필요한 기능들을 한번에 해주셨네요 감사합니다! 고생하셨어요!

2024-01-03 12:27 UTC, SoJuSo commented on src/routes/index.tsx
> +              <AuthRoute path="/profile/:id" element={<ProfilePage />} />
음...url로 직접 접근하는 경우를 생각해보면 후자의 페이지도 필요하지 않을까요! 오히려 후자의 페이지만 필요하지 않나요..?!

2024-01-03 12:27 UTC, SoJuSo commented on src/App.tsx
토큰이 리덕스 내부에 있는지 유무에 따라 처리하는 로직도 같이 구현해주셨군요..감사합니다!

2024-01-03 12:33 UTC, hellosonic-r requested changes
이렇게 로그인된 사용자가 아닐경우 로그인 페이지로 보낼 수 있군요,,어렵네요

2024-01-03 15:19 UTC, joyswim approved these changes

2024-01-04 00:08 UTC, hellosonic-r approved these changes

2024-01-04 00:08 UTC, merged