Feature/search page 0.1.0
prgrms-fe-devcourse/FEDC5_looky_heejin pull request #36
Opened 2024-01-03 12:27 UTC by joyswim

## 📝작업 내용
검색 페이지의 기본 검색 기능과 API를 연결했습니다.
> TopNavBar, Image 등 리팩토링 과정에서 공통 컴포넌트로 교체할 예정입니다.

### 컴포넌트 구조
<img src="https://github.com/prgrms-fe-devcourse/FEDC5_looky_heejin/assets/124686011/aab838a0-9516-4c27-a8ba-efbf4a0b74fb" width="600" />

- SearchPage : SearchBar의 검색 이벤트 핸들링, 뷰를 교체(RecentView, ResultsView)
  - Searchbar : 검색바
- RecentView : 최근 검색어 목록
- ResultsView : 결과페이지. 검색 결과 API 요청 후 사용자, 게시글 데이터 분리
  - UsersView : 사용자 탭
  - PostsView : 게시글 탭

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
<img src="https://github.com/prgrms-fe-devcourse/FEDC5_looky_heejin/assets/124686011/8aacf511-94ee-4c6b-84c4-4c0695de18e0" height="500"/>

## 💬리뷰 요구사항

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
> 1. 데이터 흐름에 대해 어색한 부분이 있다면 알려주세요. 현재 API 호출을 SearchResultsView에서 하고 있습니다. SearchPage에서 API를 호출하고 상태를 저장하는 방식이 좋나요?
> 2. useForm, useQuery 사용법이 올바른지 확인해주세요.
> 3. PR 분량에 대한 의견 부탁드립니다. 제가 생각하는 기본 검색 기능으로 PR 기준을 잡았는데 너무 분량이 많은 건 아닌지 고민됩니다.

2024-01-03 13:26 UTC, SoJuSo requested changes
고생하셨습니다 수영님!
일단 한번 쭉 코드를 읽어보고 실행해봤습니다! 근데 아래와 같이 실제 검색어 값을 잘 입력하고 컴포넌트가 바뀌어야하는 경우에도 바뀌지 않는 케이스가 존재했는데 원인을 못찾았어욥... 내일 한 번 더 보면서 체크해보겠습니다!
![컴포넌트바뀌지않음](https://github.com/prgrms-fe-devcourse/FEDC5_looky_heejin/assets/90549862/ec09b467-5619-4477-b9fd-7ae6f30982ba)

리뷰요구사항과 같은 경우도 내일 다시 보면서 한번에 코멘트 달도록 하겠습니다!

2024-01-03 13:26 UTC, SoJuSo commented on src/pages/SearchPage/SearchBar.tsx
> +import CONST from "./SearchPage.const";
P3; 상수파일 분리해서 사용하신 점은 좋았습니다! 하지만 네이밍을 CONST라고 하는 경우 명시적이지 않고 const 키워드랑 겹치는 느낌이 있어서 바꿔주시면 좋을 것 같다는 의견입니다. SearchPageConst 정도로 하거나 조금 더 명시적으로 하면 SearchBoxConst 가 맞을 것 같아요! 

++ 좀 더 생각해보니 이 부분에서 추후에 민호님 코드와 병합하는 과정을 거쳐야하기에 추후에 조율하시면 될 것 같아요!

2024-01-03 13:26 UTC, SoJuSo commented on src/components/SearchPage/index.ts
P4; 폴더 네이밍이 SearchPage로 되어있네요! pages내부 에 같은 폴더가 있기도 해서 폴더 명을 searchTab으로 바꾸면 어떨까요!

2024-01-03 13:26 UTC, SoJuSo commented on src/pages/SearchPage/SearchBar.tsx
> +        />
P5; 추후에 툴팁 같은 방식으로 에러메세지를 띄워주는 방향도 고민해보시면 좋을 것 같습니다!

2024-01-03 13:26 UTC, SoJuSo commented on src/pages/SearchPage/Views/SearchPostsView.tsx
> +              <Post key={post._id} src={post.image}>
P3; 이 부분에서 src에 undefined가 할당될 수 없다는 에러가 나는데... 음 이 부분은 추후에 제가 PostCard 만드는 것으로 교체해도 될 것 같아요!

2024-01-04 01:35 UTC, joyswim commented on src/pages/SearchPage/Views/SearchPostsView.tsx
> +              <Post key={post._id} src={post.image}>
map 전에 filter로 post.image가 있는지 확인하는 로직을 추가하겠습니다.

2024-01-04 09:52 UTC, OhWonJu requested changes

2024-01-04 09:52 UTC, OhWonJu commented on src/pages/SearchPage/SearchBar.tsx
> +        />
p1; Input 컴포넌트를 사용하실 때
Input 컴포넌트가 register 를 받아서 내부적으로 구조분해 할당을 하기 때문에
register={register(...)} 이런식으로 인자로서 전달해줘야합니다.

2024-01-05 00:24 UTC, OhWonJu approved these changes
고생하셨습니다!

2024-01-05 00:24 UTC, OhWonJu commented on src/pages/SearchPage/SearchBar.tsx
> +  }, [searchParams, setValue]);
p5; setValue 는 deps 에 두지 않아도 될 것 같습니다.

2024-01-05 00:24 UTC, OhWonJu commented on src/pages/SearchPage/Views/SearchResultsView.tsx
> +  });
p5; 추후 무한스크롤 + 페이지네이션을 고려하신다면
useInfiniteQuery + IntersectionObserver 조합에 대해 한번 알아보시면 좋습니다.

2024-01-05 00:24 UTC, OhWonJu commented on src/pages/SearchPage/Views/SearchResultsView.tsx
> +  }, [isSuccess]);
p5; 이러한 로직의 경우 useMemo 가 더 효율적일 것 같다는 생각이 드네요!
구현이 우선이니 참고 정도만 해주시면 될 것 같습니다.

```
const {users, posts} = useMemo(() => { 
 some filtering....
 필터링 결과 -> return {users, posts}
} , [data]);
```

2024-01-05 00:24 UTC, OhWonJu commented on src/pages/SearchPage/Views/SearchResultsView.tsx
> +  }
p5; interface 가 컴포넌트 내부에 위치할 필요는 없지 않을까요?
컴포넌트가 생성될때마다 interface 도 생성되야 하니..불필요한 자원을 낭비하게되는 것 같아요!

2024-01-05 00:24 UTC, OhWonJu commented on src/pages/SearchPage/Views/SearchResultsView.tsx
> +  }
p5; 렌더링 관련 구문이 제일 마지막에 위치하는게 자연스러운것 같습니다.
개인적으로 바온 코드드들에도 그런 형식이였구요.

handle .. 함수들
//

if(isloading)
if(error)
return ()

요런 흐름이요!

2024-01-05 00:24 UTC, OhWonJu commented on src/pages/SearchPage/index.tsx
> +  const addRecentHistory = useCallback(
여담이지만 useCallback 을 자주 사용하는 것이 꼭 좋은것만은 아닙니다.
결국은 함수를 캐싱하는 것이라 리소스를 소모하는 것은 똑같거든요.
변화에 둔감한 함수(한번 캐싱해놓으면 오래 다시 캐싱할 필요가 없는 함수) 위주로 useCallback 을 사용합니다 
또는
- 자식 컴포넌트에게 함수를 props 로 전달하는 경우 - 자식 컴포넌트를 React.memo 로 감싸는 경우
- 컴포넌트의 리렌더링이 매우 빈번한 경우 - Like 그림판
- 함수가 다른 Hook 의 deps array 에 사용되는 경우

이러한 경우에 사용됩니당.

2024-01-05 00:24 UTC, OhWonJu commented on src/pages/SearchPage/index.tsx
> +export default SearchPage;
p4; EOF 지켜주세요!

2024-01-05 01:56 UTC, SoJuSo approved these changes
원주님 피드백까지 반영 후 merge 하면 좋을 것 같습니다! 다만 이후 searchBar에 대한 UI 충돌이 약간 걱정되는데 해당 문제 발생 시 빠르게 해결 부탁드리겠습니다!

2024-01-05 02:11 UTC, joyswim commented on src/pages/SearchPage/index.tsx
> +  const addRecentHistory = useCallback(
상세한 설명 감사합니다. useCallback을 언제 사용되는지 명확하게 감이 잡히지 않았습니다. addRecentHistory의 경우 계속 반환 값이 바뀌니까 이 경우에는 useCallback을 사용하지 않는 것이 좋겠다는 것으로 이해했는데 맞나요?
공식문서를 다시 봐야겠네요!

2024-01-05 02:14 UTC, joyswim commented on src/pages/SearchPage/index.tsx
> +export default SearchPage;
prettier 기본 설정이라 신경 쓰고 있지 않았는데 충돌 해결하면서 EOF가 지켜지지 않았습니다. web 충돌 해결 시 신경 써야 겠네요.

2024-01-05 03:07 UTC, OhWonJu commented on src/pages/SearchPage/index.tsx
> +  const addRecentHistory = useCallback(
recentKeyword 가 자주 바뀐다면 그만큼 useCallback 이 내부 함수를 자주 캐싱해야한다는 것이고, 이는 캐싱을 하는 의미가 크게 없는 경우라고 볼 수 있겠습니다.
어느 기준으로 최적화를 할 것인가? 는 주관적이고/ 짬바? 에서 나오는 것 같아서 사실 저도 많이 헷갈리긴 합니다!

2024-01-05 03:26 UTC, hellosonic-r approved these changes
수영님 구현하시느라 고생하셨습니다. 고민 많이하신게 보이네요,, 
PR 내용에 컴포넌트 구조까지 명시해주셔서 이해하기 좋았습니다~👍

2024-01-05 10:13 UTC, merged